### ISSUE TITLE
figures for the wiki

### ISSUE THREAD

**Issue by pelednoam** [pelednoam/mmvt#12]
![splitted_lateral_medial_pial_white](https://cloud.githubusercontent.com/assets/1643819/21019716/86685fa4-bd3f-11e6-87b1-3b88183aa225.png)

**Comment by NataliaRozengard** [comment]
![transperent_logo_small](https://user-images.githubusercontent.com/35853195/42889397-52f9c75e-8a78-11e8-9da8-86ccc3a30a80.png)

**Comment by pelednoam** [comment]
![skull](https://user-images.githubusercontent.com/1643819/43041577-87883cdc-8d32-11e8-94c7-03aa2f462f68.png)

**Comment by alexrockhill** [comment]
![blender_remote_debug](https://user-images.githubusercontent.com/13473576/47917127-e9873d00-de7e-11e8-9ef6-f5bf0637929f.png)
![debug_launch_image](https://user-images.githubusercontent.com/13473576/47917128-e9873d00-de7e-11e8-807a-11c2a816eaa0.png)
![pycharm_debug_example_image](https://user-images.githubusercontent.com/13473576/47917129-e9873d00-de7e-11e8-9646-56ced7b9808e.png)
<img width="1013" alt="python_interpreter_setup_image" src="https://user-images.githubusercontent.com/13473576/47917130-e9873d00-de7e-11e8-911f-2b066d827bc5.png">
![remote_debugger_image](https://user-images.githubusercontent.com/13473576/47917131-e9873d00-de7e-11e8-92f8-6d6612df2cdf.png)
<img width="1074" alt="scripts_debugger_setup_image" src="https://user-images.githubusercontent.com/13473576/47917132-ea1fd380-de7e-11e8-9948-58816900f64c.png">
