### ISSUE TITLE
gifs for README

### ISSUE THREAD

**Issue by pelednoam** [pelednoam/mmvt#2]
![mmvt-meg-fmri-electrodes](https://cloud.githubusercontent.com/assets/1643819/17341371/4d3505de-58c2-11e6-8bae-91165c573a07.gif)

**Comment by pelednoam** [comment]
![meg-ttest](https://cloud.githubusercontent.com/assets/1643819/17341466/c1ac0548-58c2-11e6-9736-a85163f80521.gif)

**Comment by pelednoam** [comment]
![mg78_elecs_coh_meg_diff_5](https://cloud.githubusercontent.com/assets/1643819/17341742/03e0af80-58c4-11e6-8587-125cde58e6b8.gif)

**Comment by pelednoam** [comment]
![fmri4d-corr](https://cloud.githubusercontent.com/assets/1643819/24373139/63a21202-12fe-11e7-8acb-1efcb5f78dad.gif)

**Comment by pelednoam** [comment]
![fmri4d-corr](https://cloud.githubusercontent.com/assets/1643819/24374566/5ce2dce4-1303-11e7-9b3a-c23448e5114e.gif)

**Comment by pelednoam** [comment]
![inflating](https://user-images.githubusercontent.com/1643819/32589170-feaf4208-c4e0-11e7-9d31-761be79468a1.gif)

**Comment by pelednoam** [comment]
![inflating](https://user-images.githubusercontent.com/1643819/32613284-7cf767e2-c538-11e7-9cb5-086c6f915aef.gif)

**Comment by pelednoam** [comment]
![inflating_meg](https://user-images.githubusercontent.com/1643819/32626655-f58758be-c55d-11e7-94c6-de246c291905.gif)

**Comment by pelednoam** [comment]
![mmvt_logo_2](https://user-images.githubusercontent.com/1643819/35895658-68c489dc-0b86-11e8-95b6-253ea027d598.png)

**Comment by pelednoam** [comment]
![mmvt_logo](https://user-images.githubusercontent.com/1643819/35896839-34730e8c-0b8c-11e8-878d-186728335d0c.png)

**Comment by pelednoam** [comment]
![mmvt_logo_3](https://user-images.githubusercontent.com/1643819/35896982-ec9bf2a8-0b8c-11e8-85cc-58610e6d1f30.png)

**Comment by pelednoam** [comment]
![mmvt_logo](https://user-images.githubusercontent.com/1643819/36446044-0ba7e0b4-164e-11e8-8ff8-f2963bcf78be.png)

**Comment by pelednoam** [comment]
![trans_head](https://user-images.githubusercontent.com/1643819/39079114-4feaeab0-44e2-11e8-9f59-25bc856e13a7.png)

**Comment by pelednoam** [comment]
![trans_head_2](https://user-images.githubusercontent.com/1643819/39079174-8b61dc1a-44e3-11e8-8ce6-1c783596d1ae.png)

**Comment by NataliaRozengard** [comment]
![new_icon](https://user-images.githubusercontent.com/35853195/41723319-c8514bb2-7538-11e8-8e1b-44e3ebca04d6.png)

**Comment by NataliaRozengard** [comment]
![small_logo](https://user-images.githubusercontent.com/35853195/41723611-85a1a356-7539-11e8-9bd9-95e068085d24.png)

**Comment by NataliaRozengard** [comment]
![meg_source_sensors_head](https://user-images.githubusercontent.com/35853195/43099302-be2514a0-8e8f-11e8-9567-e23bf3b1d2e2.png)
